volumes:
  postgres_data:
  redis_data:
  media:
  static:
  logs:

services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - PGUSER=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=final_db
    ports:
      - "5435:5432"

  web:
    build: .
    command: >
      bash -c "python3 manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8001 --workers 1 --log-level 'debug'"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # - .:/src
      - ./media:/src/mediafiles
      - ./static:/src/static
      - logs:/logs
    ports:
      - "8001:8001"
    depends_on:
      - db

  redis:
    restart: unless-stopped
    image: redis:alpine
    command: redis-server --requirepass OMeDuTERnUtH
    ports:
      - "6370:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    command: celery -A config worker -l info
    depends_on:
      - redis
