name: Deploy Django with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server via SSH
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SERVER_IP: ${{ secrets.SSH_IP }}
      run: |
        sudo apt-get update && sudo apt-get install -y sshpass
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << EOF
          cd aza/final_backend/
          git pull origin main
          docker compose down && docker compose up --build -d
        EOF